array and basics


In [1]:
import numpy as np

Creating array from list

In [3]:
array_1d = np.array([1,2,3,4,5])
print(array_1d)
print(array_1d[2])

[1 2 3 4 5]
3


In [4]:
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]
