array and basics


In [1]:
import numpy as np

Creating array from list

In [3]:
array_1d = np.array([1,2,3,4,5])
print(array_1d)
print(array_1d[2])

[1 2 3 4 5]
3


In [4]:
array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


Numpy VS List Array

In [3]:

py_list = [1,2,3,4,5]
print("List Multipliation", py_list * 2)

np_array = np.array([1,2,3,4,5])
print("Numpy multiplication", np_array * 2)

#Numpy operation is faster than list operation

List Multipliation [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy multiplication [ 2  4  6  8 10]


Creating matrix

In [14]:
ones = np.ones((2,3))
print(ones, "\n")

zeros = np.zeros((4,5))
print("\n",zeros)

full = np.full((2,2),9)
print("\n",full)

random = np.random.random((2,3))
print("\n", random)

sequence = np.arange(0, 10, 3)
print(sequence)




[[1. 1. 1.]
 [1. 1. 1.]] 


 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[9 9]
 [9 9]]

 [[0.40638726 0.76788743 0.06612258]
 [0.57377736 0.42241067 0.40972765]]
[0 3 6 9]


Vector, Matrix and Tensor

In [17]:
vector = np.array([1,2,3])
print("Vetor : ", vector)

matrix = np.array([[1,2,3], [4,5,6]])
print("\nMatrix : ", matrix)

Vetor :  [1 2 3]

Matrix :  [[1 2 3]
 [4 5 6]]
